"""added banner image column

Revision ID: 30a1800db7b0
Revises: 454e92d0b400
Create Date: 2026-04-27 23:26:28.244821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a1800db7b0'
down_revision = '454e92d0b400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(), server_default='default_banner.png', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner_image')

    # ### end Alembic commands ###
