"""initial migration with user times

Revision ID: 4c02eceddc87
Revises: 
Create Date: 2026-04-04 22:07:32.864674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c02eceddc87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('volume_time', sa.Float(), nullable=True),
    sa.Column('brightness_time', sa.Float(), nullable=True),
    sa.Column('maze_time', sa.Float(), nullable=True),
    sa.Column('tnc_quiz_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
