"""added sign up and sign in logic from medium @cecilia chimento article

Revision ID: 9527a1fea730
Revises: 9cacf9b0a3a9
Create Date: 2026-04-20 18:43:28.165920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9527a1fea730'
down_revision = '9cacf9b0a3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('volume_time', sa.FLOAT(), nullable=True),
    sa.Column('brightness_time', sa.FLOAT(), nullable=True),
    sa.Column('maze_time', sa.FLOAT(), nullable=True),
    sa.Column('tnc_quiz_time', sa.FLOAT(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
