"""added score table for multiple tasks

Revision ID: 0d611560eff4
Revises: 30a1800db7b0
Create Date: 2026-04-29 14:56:01.721948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d611560eff4'
down_revision = '30a1800db7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=False),
    sa.Column('best_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('maze_time')
        batch_op.drop_column('brightness_time')
        batch_op.drop_column('volume_time')
        batch_op.drop_column('tnc_quiz_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tnc_quiz_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('volume_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('brightness_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('maze_time', sa.FLOAT(), nullable=True))

    op.drop_table('score')
    # ### end Alembic commands ###
