"""added profile image column

Revision ID: 454e92d0b400
Revises: ad51e2fc3a59
Create Date: 2026-04-21 11:19:22.242091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454e92d0b400'
down_revision = 'ad51e2fc3a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), server_default='icon_head.jpg', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
