"""initial migration

Revision ID: ad51e2fc3a59
Revises: 
Create Date: 2026-04-20 19:55:09.208922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad51e2fc3a59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('volume_time', sa.Float(), nullable=True),
    sa.Column('brightness_time', sa.Float(), nullable=True),
    sa.Column('maze_time', sa.Float(), nullable=True),
    sa.Column('tnc_quiz_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
